--
-- Supabase Database Schema
-- Generated via: pg_dump -h db.<project-id>.supabase.co -p 5432 -U postgres -d postgres -n public --schema-only --no-owner --no-privileges
-- Usage: Copy content to Supabase SQL Editor and run to initialize database.
--

--
-- PostgreSQL database dump
--

\restrict ECutbdUoRqzxsnU002Qao3zo08qsV2N9e0LSEazsjmEu5UgdYTNW4kv2WUVkZze

-- Dumped from database version 17.6
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: notes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notes (
    id bigint NOT NULL,
    content text,
    user_id uuid DEFAULT auth.uid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now(),
    embedding extensions.vector(512)
);


--
-- Name: hybrid_search_notes(text, extensions.vector, integer, double precision, double precision, integer); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.hybrid_search_notes(query_text text, query_embedding extensions.vector, match_count integer, full_text_weight double precision DEFAULT 1.0, semantic_weight double precision DEFAULT 1.0, rrf_k integer DEFAULT 50) RETURNS SETOF public.notes
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'public', 'extensions'
    AS $$
BEGIN
  RETURN QUERY
  WITH full_text AS (
    SELECT
      notes.id,
      row_number() OVER (ORDER BY pgroonga_score(tableoid, ctid) DESC) AS rank_ix
    FROM notes
    WHERE notes.content &@~ query_text
    ORDER BY rank_ix
    LIMIT least(match_count, 30) * 2
  ),
  semantic AS (
    SELECT
      notes.id,
      row_number() OVER (ORDER BY notes.embedding <=> query_embedding) AS rank_ix
    FROM notes
    WHERE notes.embedding IS NOT NULL
    ORDER BY rank_ix
    LIMIT least(match_count, 30) * 2
  )
  SELECT notes.*
  FROM full_text
  FULL OUTER JOIN semantic ON full_text.id = semantic.id
  JOIN notes ON coalesce(full_text.id, semantic.id) = notes.id
  ORDER BY
    coalesce(1.0 / (rrf_k + full_text.rank_ix), 0.0) * full_text_weight +
    coalesce(1.0 / (rrf_k + semantic.rank_ix), 0.0) * semantic_weight
    DESC
  LIMIT least(match_count, 30);
END;
$$;


--
-- Name: update_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'public'
    AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;


--
-- Name: hobbies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hobbies (
    id bigint NOT NULL,
    user_id uuid DEFAULT auth.uid() NOT NULL,
    hobby_id text NOT NULL,
    title text NOT NULL,
    date date NOT NULL,
    rating bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    type text NOT NULL,
    channel text,
    poster text
);


--
-- Name: movies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.hobbies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: places; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.places (
    id bigint NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    city text,
    visited_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid NOT NULL,
    country text NOT NULL,
    priority bigint
);


--
-- Name: places_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.places ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.places_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hobbies hobbies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hobbies
    ADD CONSTRAINT hobbies_pkey PRIMARY KEY (id);


--
-- Name: notes notes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT notes_pkey PRIMARY KEY (id);


--
-- Name: places places_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.places
    ADD CONSTRAINT places_pkey PRIMARY KEY (id);


--
-- Name: hobbies_hobby_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX hobbies_hobby_id_idx ON public.hobbies USING btree (hobby_id);


--
-- Name: hobbies_user_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX hobbies_user_id_idx ON public.hobbies USING btree (user_id);


--
-- Name: notes_content_pgroonga_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notes_content_pgroonga_idx ON public.notes USING pgroonga (content);


--
-- Name: notes_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notes_created_at_idx ON public.notes USING btree (created_at);


--
-- Name: notes_embedding_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notes_embedding_idx ON public.notes USING hnsw (embedding extensions.vector_cosine_ops);


--
-- Name: notes_user_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notes_user_id_idx ON public.notes USING btree (user_id);


--
-- Name: notes notes_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER notes_updated_at BEFORE UPDATE ON public.notes FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


--
-- Name: hobbies movies_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hobbies
    ADD CONSTRAINT movies_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;


--
-- Name: notes notes_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;


--
-- Name: places places_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.places
    ADD CONSTRAINT places_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;


--
-- Name: hobbies delete_admin; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY delete_admin ON public.hobbies FOR DELETE TO authenticated USING ((((( SELECT auth.jwt() AS jwt) -> 'app_metadata'::text) ->> 'role'::text) = 'admin'::text));


--
-- Name: places delete_admin; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY delete_admin ON public.places FOR DELETE TO authenticated USING ((((( SELECT auth.jwt() AS jwt) -> 'app_metadata'::text) ->> 'role'::text) = 'admin'::text));


--
-- Name: notes delete_owner; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY delete_owner ON public.notes FOR DELETE TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: hobbies; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.hobbies ENABLE ROW LEVEL SECURITY;

--
-- Name: hobbies insert_admin; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY insert_admin ON public.hobbies FOR INSERT TO authenticated WITH CHECK (((((( SELECT auth.jwt() AS jwt) -> 'app_metadata'::text) ->> 'role'::text) = 'admin'::text) AND (( SELECT auth.uid() AS uid) = user_id)));


--
-- Name: places insert_admin; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY insert_admin ON public.places FOR INSERT TO authenticated WITH CHECK (((((( SELECT auth.jwt() AS jwt) -> 'app_metadata'::text) ->> 'role'::text) = 'admin'::text) AND (( SELECT auth.uid() AS uid) = user_id)));


--
-- Name: notes insert_owner; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY insert_owner ON public.notes FOR INSERT TO authenticated WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: notes; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;

--
-- Name: places; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.places ENABLE ROW LEVEL SECURITY;

--
-- Name: hobbies select_all; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY select_all ON public.hobbies FOR SELECT USING (true);


--
-- Name: notes select_all; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY select_all ON public.notes FOR SELECT USING (true);


--
-- Name: places select_all; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY select_all ON public.places FOR SELECT USING (true);


--
-- Name: hobbies update_admin; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY update_admin ON public.hobbies FOR UPDATE TO authenticated USING ((((( SELECT auth.jwt() AS jwt) -> 'app_metadata'::text) ->> 'role'::text) = 'admin'::text)) WITH CHECK ((((( SELECT auth.jwt() AS jwt) -> 'app_metadata'::text) ->> 'role'::text) = 'admin'::text));


--
-- Name: places update_admin; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY update_admin ON public.places FOR UPDATE TO authenticated USING ((((( SELECT auth.jwt() AS jwt) -> 'app_metadata'::text) ->> 'role'::text) = 'admin'::text)) WITH CHECK ((((( SELECT auth.jwt() AS jwt) -> 'app_metadata'::text) ->> 'role'::text) = 'admin'::text));


--
-- Name: notes update_owner; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY update_owner ON public.notes FOR UPDATE TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));


--
-- PostgreSQL database dump complete
--

\unrestrict ECutbdUoRqzxsnU002Qao3zo08qsV2N9e0LSEazsjmEu5UgdYTNW4kv2WUVkZze

